# Generated by Django 5.1.7 on 2025-03-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_videopost_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название видео'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video_file',
            field=models.FileField(upload_to='videos/', verbose_name='Загружаемый видео-файл формата MP4'),
        ),
    ]
