# Generated by Django 5.1.7 on 2025-03-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_videopost_title_alter_videopost_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='category',
            field=models.CharField(default='none', max_length=50, verbose_name='Категория видео'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='desc',
            field=models.TextField(verbose_name='ОПодробное описание к видео'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='thumbnail',
            field=models.ImageField(default='none', upload_to='videos/thumbnail/', verbose_name='Титульная картинка формата JPG'),
        ),
    ]
