# Generated by Django 5.1.7 on 2025-03-14 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_videopost_dislikes_alter_videopost_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_create',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='category',
            field=models.CharField(choices=[('Science & Technology', 'Science & Technology'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Education', 'Education'), ('Blogs', 'Blogs')], default='Blogs', max_length=120, verbose_name='Категория видео'),
        ),
    ]
