# Generated by Django 5.1.7 on 2025-03-30 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment_date_create_alter_videopost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Факультет')),
                ('logo', models.ImageField(blank=True, upload_to='pic/faculty/')),
                ('date_create', models.DateField(default=datetime.date.today, verbose_name='Дата создания записи')),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='year_entering',
            field=models.DateField(blank=True, default='1970-01-01', verbose_name='Год поступления в университет'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='desc',
            field=models.TextField(verbose_name='Подробное описание к видео'),
        ),
    ]
