# Generated by Django 5.1.7 on 2025-03-30 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_faculty_userdata_year_entering_alter_videopost_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.faculty'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='logo',
            field=models.ImageField(blank=True, upload_to='pic/faculty/', verbose_name='Герб факультета'),
        ),
    ]
