# Generated by Django 5.1.7 on 2025-03-30 12:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userdata_faculty_alter_faculty_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Наименование специальности')),
                ('code', models.CharField(max_length=10, verbose_name='Код специальности')),
                ('date_create', models.DateField(default=datetime.date.today, verbose_name='Дата создания записи')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.faculty')),
            ],
        ),
    ]
