# Generated by Django 5.1.7 on 2025-03-30 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='direction',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='main.direction'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='code',
            field=models.CharField(max_length=18, verbose_name='Код специальности'),
        ),
    ]
