# Generated by Django 5.1.7 on 2025-03-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userdata_direction_alter_direction_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='faculty',
        ),
    ]
